import { define_crud, define_module } from "@opus-perpetuus/imperium-core-kit";
import { medical_file_pages } from "./medical-file.pages.ts";
import { medical_file_tables } from "./medical-file.tables.ts";

export const medical_file_module = define_module({
  resource: "medical-file",
  labels: {
    singular: "Expediente clínico",
    plural: "Expediente clínico",
    read: "Ver Expediente clínico",
    write: "Editar Expediente clínico",
  },
  routes: define_crud({
    resource: "medical-file",
    table: "medical_file",
    soft_delete: true,
    soft_delete_field: "is_active",
    history: true,
    default_sort: "name:asc",
    id_prefix: "medical-",
    fields: {
      name: { type: "string", required: true, search: true },
      description: { type: "string", search: true },
      is_active: { type: "boolean" },
      state: { type: "string" },
      ref: { type: "string", search: true },
      search_field: { type: "string", search: true },
      created_by: { type: "string" },
      custom_data: { type: "json" },
      payload: { type: "json" },
      paciente_id: { type: "string", search: true },
      numero_expediente: { type: "string", search: true },
      nombre_paciente: { type: "string", search: true },
      fecha_consulta: { type: "string", search: true },
      hora_consulta: { type: "string", search: true },
      status: { type: "string", search: true },
      enfermedad: { type: "string", search: true },
      presente: { type: "boolean" },
      comentarios: { type: "string", search: true },
      menarca: { type: "number" },
      ritmo_menstrual: { type: "string", search: true },
      dismenorrhea: { type: "string", search: true },
      fum: { type: "string", search: true },
      ivsa: { type: "number" },
      numero_parejas: { type: "number" },
      gesta: { type: "number" },
      partos: { type: "number" },
      abortos: { type: "number" },
      cesareas: { type: "number" },
      fpp: { type: "string", search: true },
      fup: { type: "string", search: true },
      menopausia: { type: "string", search: true },
      metodo_planificacion: { type: "string", search: true },
      mastografia: { type: "string", search: true },
      ta: { type: "string", search: true },
      fc: { type: "number" },
      fr: { type: "number" },
      temperatura: { type: "number" },
      peso: { type: "number" },
      talla: { type: "number" },
      imc: { type: "number" },
      saturacion_o2: { type: "number" },
      medico_tratante_id: { type: "string", search: true },
      enfermedades_actuales: { type: "string", search: true },
      quirurgicos: { type: "string", search: true },
      transfusiones: { type: "string", search: true },
      traumaticos: { type: "string", search: true },
      hospitalizaciones_previas: { type: "string", search: true },
      alergias_detalladas: { type: "string", search: true },
      tipo_vivienda: { type: "string", search: true },
      servicios_basicos: { type: "boolean" },
      alimentacion: { type: "string", search: true },
      tabaquismo: { type: "string", search: true },
      alcohol: { type: "string", search: true },
      otras_sustancias: { type: "string", search: true },
      actividad_fisica: { type: "string", search: true },
      imunizaciones: { type: "string", search: true },
      gineco_obstetrico: { type: "string", search: true },
      sintomas_generales: { type: "string", search: true },
      piel_anexos: { type: "string", search: true },
      cabeza_cuello: { type: "string", search: true },
      respiratorio: { type: "string", search: true },
      cardiovascular: { type: "string", search: true },
      digestivo: { type: "string", search: true },
      genitourinario: { type: "string", search: true },
      musculoesqueletico: { type: "string", search: true },
      neurologico: { type: "string", search: true },
      psiquiatrico_endocrino: { type: "string", search: true },
      otros_sintomas: { type: "string", search: true },
      habitus_exterior: { type: "string", search: true },
      signos_vitales: { type: "string", search: true },
      exploracion_por_aparatos: { type: "string", search: true },
      impresion_diagnostica: { type: "string", search: true },
      tratamiento_farmacologico: { type: "string", search: true },
      indicaciones_no_farmacologicas: { type: "string", search: true },
      estudios_solicitados: { type: "string", search: true },
      interconsultas: { type: "string", search: true },
      pronostico: { type: "string", search: true },
      proxima_cita: { type: "string", search: true },
      nombre_medico_firma: { type: "string", search: true },
      cedula_profesional: { type: "string", search: true },
      firma_digital: { type: "string", search: true },
    },
    options_map: { value: "id", label: "name" },
  }),
  tables: medical_file_tables,
  pages: medical_file_pages,
  menu: [
    {
      id: "control-hospitalario.medical-file",
      label: "Expediente clínico",
      order: 0,
      pageId: "control-hospitalario.medical-file",
      path: "medical-file",
      permission: "subject.control-hospitalario.medical-file.read",
      icon: "document",
    },
    {
      id: "control-hospitalario.medical",
      label: "Médicos",
      order: 0,
      pageId: "control-hospitalario.medical",
      path: "medical",
      permission: "subject.control-hospitalario.medical.read",
      icon: "document",
    },
    {
      id: "control-hospitalario.patient",
      label: "Pacientes",
      order: 0,
      pageId: "control-hospitalario.patient",
      path: "patient",
      permission: "subject.control-hospitalario.patient.read",
      icon: "document",
    },
    {
      id: "control-hospitalario.kiosk",
      label: "Kiosco Expediente Clínico",
      order: 1,
      pageId: "control-hospitalario.kiosk",
      path: "kiosk",
      permission: "subject.control-hospitalario.kiosk.read",
      icon: "document",
    }
    ],
});
