import {
  build_feature_shell_page,
  type KirletPageDecl,
} from "@opus-perpetuus/imperium-core-kit";

const API = "api://m/subject-control-hospitalario";

export const medical_file_pages: KirletPageDecl[] = [
  {
    id: "control-hospitalario.medical-file",
    path: "medical-file",
    permission: "subject.control-hospitalario.medical-file.read",
    build: () =>
      build_feature_shell_page({
        id: "control-hospitalario.medical-file",
        owner: "subject-control-hospitalario",
        title: "Expediente clínico",
        props: {
          basePath: "medical-file",
          idKey: "id",
          nameKey: "name",
          view: {
            title: "Expediente clínico",
            subtitle: "Submenú de control-hospitalario",
            pluralLabel: "expediente clínico",
            singularLabel: "expediente clínico",
            emptyTitle: "Sin registros",
            emptyDescription: "Migra desde Mongo o crea el primero",
          },
          data: {
            list: `${API}/medical-file`,
            record: `${API}/medical-file/:id`,
            create: { method: "POST", action: `${API}/medical-file` },
            update: { method: "PATCH", action: `${API}/medical-file/:id` },
            delete: { method: "DELETE", action: `${API}/medical-file/:id` },
          },
          table: {
            columns: [
              { key: "name", label: "Nombre", sortable: true, priority: 1 },
              { key: "is_active", label: "Activo", sortable: true, priority: 2 },
              { key: "ref", label: "Ref", sortable: true, priority: 3 },
              { key: "paciente_id", label: "paciente id", sortable: true, priority: 3 },
              { key: "numero_expediente", label: "numero expediente", sortable: true, priority: 3 },
              { key: "nombre_paciente", label: "nombre paciente", sortable: true, priority: 3 },
              { key: "fecha_consulta", label: "fecha consulta", sortable: true, priority: 3 },
              { key: "hora_consulta", label: "hora consulta", sortable: true, priority: 3 },
              { key: "status", label: "status", sortable: true, priority: 3 },
            ],
            fillHeight: true,
            serverQuery: true,
          },
          form: {
            fields: [
              { name: "name", component: "input-text", label: "Nombre", required: true },
              { name: "description", component: "input-textarea", label: "Descripción" },
              { name: "ref", component: "input-text", label: "Referencia (_ref)" },
              { name: "paciente_id", component: "input-datalist", label: "paciente id", optionsSource: "api://m/subject-control-hospitalario/patient?as=options&limite=1000" },
              { name: "numero_expediente", component: "input-text", label: "numero expediente" },
              { name: "nombre_paciente", component: "input-text", label: "nombre paciente" },
              { name: "fecha_consulta", component: "input-date", label: "fecha consulta" },
              { name: "hora_consulta", component: "input-time", label: "hora consulta" },
              { name: "status", component: "input-text", label: "status" },
              { name: "enfermedad", component: "input-textarea", label: "enfermedad" },
              { name: "presente", component: "input-checkbox", label: "presente" },
              { name: "comentarios", component: "input-textarea", label: "comentarios" },
              { name: "menarca", component: "input-number", label: "menarca" },
              { name: "ritmo_menstrual", component: "input-textarea", label: "ritmo menstrual" },
              { name: "dismenorrhea", component: "input-textarea", label: "dismenorrhea" },
              { name: "fum", component: "input-date", label: "fum" },
              { name: "ivsa", component: "input-number", label: "ivsa" },
              { name: "numero_parejas", component: "input-number", label: "numero parejas" },
              { name: "gesta", component: "input-number", label: "gesta" },
              { name: "partos", component: "input-number", label: "partos" },
              { name: "abortos", component: "input-number", label: "abortos" },
              { name: "cesareas", component: "input-number", label: "cesareas" },
              { name: "fpp", component: "input-date", label: "fpp" },
              { name: "fup", component: "input-date", label: "fup" },
              { name: "menopausia", component: "input-textarea", label: "menopausia" },
              { name: "metodo_planificacion", component: "input-textarea", label: "metodo planificacion" },
              { name: "mastografia", component: "input-textarea", label: "mastografia" },
              { name: "ta", component: "input-text", label: "ta" },
              { name: "fc", component: "input-number", label: "fc" },
              { name: "fr", component: "input-number", label: "fr" },
              { name: "temperatura", component: "input-number", label: "temperatura" },
              { name: "peso", component: "input-number", label: "peso" },
              { name: "talla", component: "input-number", label: "talla" },
              { name: "imc", component: "input-number", label: "imc" },
              { name: "saturacion_o2", component: "input-number", label: "saturacion o2" },
              { name: "medico_tratante_id", component: "input-datalist", label: "medico tratante id", optionsSource: "api://m/subject-control-hospitalario/medical?as=options&limite=1000" },
              { name: "enfermedades_actuales", component: "input-textarea", label: "enfermedades actuales" },
              { name: "quirurgicos", component: "input-textarea", label: "quirurgicos" },
              { name: "transfusiones", component: "input-textarea", label: "transfusiones" },
              { name: "traumaticos", component: "input-textarea", label: "traumaticos" },
              { name: "hospitalizaciones_previas", component: "input-textarea", label: "hospitalizaciones previas" },
              { name: "alergias_detalladas", component: "input-textarea", label: "alergias detalladas" },
              { name: "tipo_vivienda", component: "input-text", label: "tipo vivienda" },
              { name: "servicios_basicos", component: "input-checkbox", label: "servicios basicos" },
              { name: "alimentacion", component: "input-textarea", label: "alimentacion" },
              { name: "tabaquismo", component: "input-textarea", label: "tabaquismo" },
              { name: "alcohol", component: "input-textarea", label: "alcohol" },
              { name: "otras_sustancias", component: "input-textarea", label: "otras sustancias" },
              { name: "actividad_fisica", component: "input-textarea", label: "actividad fisica" },
              { name: "imunizaciones", component: "input-textarea", label: "imunizaciones" },
              { name: "gineco_obstetrico", component: "input-textarea", label: "gineco obstetrico" },
              { name: "sintomas_generales", component: "input-textarea", label: "sintomas generales" },
              { name: "piel_anexos", component: "input-textarea", label: "piel anexos" },
              { name: "cabeza_cuello", component: "input-textarea", label: "cabeza cuello" },
              { name: "respiratorio", component: "input-textarea", label: "respiratorio" },
              { name: "cardiovascular", component: "input-textarea", label: "cardiovascular" },
              { name: "digestivo", component: "input-textarea", label: "digestivo" },
              { name: "genitourinario", component: "input-textarea", label: "genitourinario" },
              { name: "musculoesqueletico", component: "input-textarea", label: "musculoesqueletico" },
              { name: "neurologico", component: "input-textarea", label: "neurologico" },
              { name: "psiquiatrico_endocrino", component: "input-textarea", label: "psiquiatrico endocrino" },
              { name: "otros_sintomas", component: "input-textarea", label: "otros sintomas" },
              { name: "habitus_exterior", component: "input-textarea", label: "habitus exterior" },
              { name: "signos_vitales", component: "input-textarea", label: "signos vitales" },
              { name: "exploracion_por_aparatos", component: "input-textarea", label: "exploracion por aparatos" },
              { name: "impresion_diagnostica", component: "input-textarea", label: "impresion diagnostica" },
              { name: "tratamiento_farmacologico", component: "input-textarea", label: "tratamiento farmacologico" },
              { name: "indicaciones_no_farmacologicas", component: "input-textarea", label: "indicaciones no farmacologicas" },
              { name: "estudios_solicitados", component: "input-textarea", label: "estudios solicitados" },
              { name: "interconsultas", component: "input-textarea", label: "interconsultas" },
              { name: "pronostico", component: "input-textarea", label: "pronostico" },
              { name: "proxima_cita", component: "input-date", label: "proxima cita" },
              { name: "nombre_medico_firma", component: "input-text", label: "nombre medico firma" },
              { name: "cedula_profesional", component: "input-text", label: "cedula profesional" },
              { name: "firma_digital", component: "input-signature", label: "firma digital" },
            ],
          },
        },
      }),
  },
];
