import type { KirletTableDecl } from "@opus-perpetuus/imperium-core-kit";

export const kiosk_tables: KirletTableDecl[] = [
  {
    name: "kiosk",
    columns: [
      { name: "id", type: "text", primaryKey: true },
      { name: "name", type: "text", notNull: true },
      { name: "description", type: "text" },
      { name: "is_active", type: "boolean", notNull: true, default: true },
      { name: "state", type: "text" },
      { name: "ref", type: "text", unique: true },
      { name: "search_field", type: "text" },
      { name: "created_by", type: "text" },
      { name: "custom_data", type: "json" },
      { name: "payload", type: "json" },
      { name: "created_at", type: "text", notNull: true },
      { name: "updated_at", type: "text", notNull: true },
      { name: "paciente_id", type: "text" },
      { name: "numero_expediente", type: "text" },
      { name: "nombre_paciente", type: "text" },
      { name: "fecha_consulta", type: "text" },
      { name: "hora_consulta", type: "text" },
      { name: "status", type: "text" },
      { name: "enfermedad", type: "text" },
      { name: "presente", type: "boolean" },
      { name: "comentarios", type: "text" },
      { name: "menarca", type: "real" },
      { name: "ritmo_menstrual", type: "text" },
      { name: "dismenorrhea", type: "text" },
      { name: "fum", type: "text" },
      { name: "ivsa", type: "real" },
      { name: "numero_parejas", type: "real" },
      { name: "gesta", type: "real" },
      { name: "partos", type: "real" },
      { name: "abortos", type: "real" },
      { name: "cesareas", type: "real" },
      { name: "fpp", type: "text" },
      { name: "fup", type: "text" },
      { name: "menopausia", type: "text" },
      { name: "metodo_planificacion", type: "text" },
      { name: "mastografia", type: "text" },
      { name: "ta", type: "text" },
      { name: "fc", type: "real" },
      { name: "fr", type: "real" },
      { name: "temperatura", type: "real" },
      { name: "peso", type: "real" },
      { name: "talla", type: "real" },
      { name: "imc", type: "real" },
      { name: "saturacion_o2", type: "real" },
      { name: "medico_tratante_id", type: "text" },
      { name: "enfermedades_actuales", type: "text" },
      { name: "quirurgicos", type: "text" },
      { name: "transfusiones", type: "text" },
      { name: "traumaticos", type: "text" },
      { name: "hospitalizaciones_previas", type: "text" },
      { name: "alergias_detalladas", type: "text" },
      { name: "tipo_vivienda", type: "text" },
      { name: "servicios_basicos", type: "boolean" },
      { name: "alimentacion", type: "text" },
      { name: "tabaquismo", type: "text" },
      { name: "alcohol", type: "text" },
      { name: "otras_sustancias", type: "text" },
      { name: "actividad_fisica", type: "text" },
      { name: "imunizaciones", type: "text" },
      { name: "gineco_obstetrico", type: "text" },
      { name: "sintomas_generales", type: "text" },
      { name: "piel_anexos", type: "text" },
      { name: "cabeza_cuello", type: "text" },
      { name: "respiratorio", type: "text" },
      { name: "cardiovascular", type: "text" },
      { name: "digestivo", type: "text" },
      { name: "genitourinario", type: "text" },
      { name: "musculoesqueletico", type: "text" },
      { name: "neurologico", type: "text" },
      { name: "psiquiatrico_endocrino", type: "text" },
      { name: "otros_sintomas", type: "text" },
      { name: "habitus_exterior", type: "text" },
      { name: "signos_vitales", type: "text" },
      { name: "exploracion_por_aparatos", type: "text" },
      { name: "impresion_diagnostica", type: "text" },
      { name: "tratamiento_farmacologico", type: "text" },
      { name: "indicaciones_no_farmacologicas", type: "text" },
      { name: "estudios_solicitados", type: "text" },
      { name: "interconsultas", type: "text" },
      { name: "pronostico", type: "text" },
      { name: "proxima_cita", type: "text" },
      { name: "nombre_medico_firma", type: "text" },
      { name: "cedula_profesional", type: "text" },
      { name: "firma_digital", type: "text" },
    ],
    indexes: [
      { name: "idx_kiosk_name", columns: ["name"] },
      { name: "idx_kiosk_active", columns: ["is_active"] },
    ],
  },
];
