import { define_crud, define_module } from "@opus-perpetuus/imperium-core-kit";
import { patient_pages } from "./patient.pages.ts";
import { patient_tables } from "./patient.tables.ts";

export const patient_module = define_module({
  resource: "patient",
  labels: {
    singular: "Pacientes",
    plural: "Pacientes",
    read: "Ver Pacientes",
    write: "Editar Pacientes",
  },
  routes: define_crud({
    resource: "patient",
    table: "patient",
    soft_delete: true,
    soft_delete_field: "is_active",
    history: true,
    default_sort: "name:asc",
    id_prefix: "patient",
    fields: {
      name: { type: "string", required: true, search: true },
      description: { type: "string", search: true },
      is_active: { type: "boolean" },
      state: { type: "string" },
      ref: { type: "string", search: true },
      search_field: { type: "string", search: true },
      created_by: { type: "string" },
      custom_data: { type: "json" },
      payload: { type: "json" },
      numero_expediente: { type: "string", search: true },
      nombre_completo: { type: "string", search: true },
      fecha_nacimiento: { type: "string", search: true },
      edad: { type: "number" },
      sexo: { type: "string", search: true },
      estado_civil: { type: "string", search: true },
      ocupacion: { type: "string", search: true },
      telefono_paciente: { type: "string", search: true },
      domicilio_completo: { type: "string", search: true },
      telefono_familiar: { type: "string", search: true },
      grupo_etnico: { type: "string", search: true },
      alergias_conocidas: { type: "string", search: true },
      adicciones: { type: "string", search: true },
    },
    options_map: { value: "id", label: "name" },
  }),
  tables: patient_tables,
  pages: patient_pages,
  menu: [],
});
